version: "3.9"
services:
  adapter:
    build: .
    image: gcr.io/tracer-external-adapters/opensea_nft
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - OPENSEA_KEY=${OPENSEA_KEY}
      - PORT=${PORT}
      - NAME=${NAME}
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
    restart: always